# Unbind the default prefix
unbind C-b

# Set prefix to C-a
set-option -g prefix C-a

# Double C-a for other apps
bind-key C-a send-prefix

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g status-style "bg=default"
set -g window-status-style "bg=#7aa2f7 fg=black"
set -g window-status-current-style "bg=#bb9af7 fg=black"
set -g status-right "#[bg=#9ece6a,fg=black] Sustayne %H:%M %d-%b-%Y"
set -g status-left "#[bg=#e0af68,fg=black,bold] [#S] #[bg=default] "
set -g status-left-length 40
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g mouse on
set-option -g destroy-unattached off

# Vim keybinds for split pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Custom keybinds
bind X kill-session

